# Generated by Django 5.1.3 on 2024-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_period",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
